 const HRM_KEYS = {
    EMPLOYEE: "EMPLOYEE",
    DEPARTMENT: "DEPARTMENT",
    RECRUIT: "RECRUIT",
    ELEARNING: "ELEARNING",
    TIMEKEEPING: "TIMEKEEPING",
    PAYROLL: "PAYROLL",
    WELFARE: "WELFARE",
    INSURANCE: "INSURANCE",
    BOOKING: "BOOKING",
    OFFER: "OFFER",
    CTV: "CTV",
    CTP: "CTP",
  };
  
 const SYSTEM_KEYS = {
    WEB_APP: 'WEB_APP'
}

export { HRM_KEYS, SYSTEM_KEYS  }
